version: "3"

services:
    backend:
        container_name: todo_crud
        env_file:
            - .env
        restart: always
        ports:
            - 8000:8000
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres

    postgres:
        image: postgres:12.9-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        ports:
            - "5433:5432"
